// Data pelanggan per wilayah.
// Format setiap baris: { kota, area, cluster, favorit: [produk, ...], harga: number|null }
// harga dalam Rupiah. Gunakan null jika data harga belum tersedia.
// Untuk menambah data baru, cukup tambahkan objek baru ke array CLUSTER_DATA di bawah.

const CLUSTER_DATA = [
  { kota: "Jakarta Barat", area: "Cengkareng", cluster: "Apt. City Park", favorit: [], harga: 350000 },
  { kota: "Jakarta Barat", area: "Cengkareng", cluster: "City Resort Malibu", favorit: [], harga: 350000 },
  { kota: "Jakarta Barat", area: "Cengkareng", cluster: "Green Court", favorit: ["EQUIDE AquaCleanse", "EQUIDE NEO Filter"], harga: 350000 },
  { kota: "Jakarta Barat", area: "Cengkareng", cluster: "Seruni", favorit: [], harga: 350000 },
  { kota: "Jakarta Barat", area: "Cengkareng", cluster: "Taman Palem Lestari", favorit: ["EQUIDE Clear", "holiv ClearWater", "holiv EasyClean"], harga: 300000 },
  { kota: "Jakarta Barat", area: "Citra", cluster: "Citra 2", favorit: ["EQUIDE AquaCleanse"], harga: 300000 },
  { kota: "Jakarta Barat", area: "Citra", cluster: "Citra 2 Ext", favorit: ["EQUIDE AquaCleanse"], harga: 300000 },
  { kota: "Jakarta Barat", area: "Citra", cluster: "Citra 3", favorit: ["EQUIDE AquaCleanse"], harga: 300000 },
  { kota: "Jakarta Barat", area: "Citra", cluster: "Citra 5", favorit: ["EQUIDE AquaCleanse", "EQUIDE NEO Filter"], harga: 300000 },
  { kota: "Jakarta Barat", area: "Citra", cluster: "Citra 6", favorit: [], harga: 300000 },
  { kota: "Jakarta Barat", area: "Citra", cluster: "Citra 6 Orange Heliconia", favorit: [], harga: 300000 },
  { kota: "Jakarta Barat", area: "Citra", cluster: "Citra 6 Yellow Chrysant", favorit: [], harga: 300000 },
  { kota: "Jakarta Barat", area: "Citra", cluster: "Citra 8 AeroMansion", favorit: ["EQUIDE AquaCleanse", "EQUIDE NEO Filter"], harga: 300000 },
  { kota: "Jakarta Barat", area: "Citra", cluster: "Citra 8 AeroVille", favorit: ["EQUIDE AquaCleanse", "EQUIDE NEO Filter"], harga: 300000 },
  { kota: "Jakarta Barat", area: "Citra", cluster: "Citra 8 Malta", favorit: ["EQUIDE AquaCleanse", "EQUIDE NEO Filter"], harga: 300000 },
  { kota: "Jakarta Barat", area: "Citra", cluster: "CitraLake Villa", favorit: [], harga: 300000 },
  { kota: "Jakarta Barat", area: "Golf Lake", cluster: "Atlantic City", favorit: ["EQUIDE Clear", "EQUIDE NEO Filter"], harga: 350000 },
  { kota: "Jakarta Barat", area: "Golf Lake", cluster: "Sand Hill", favorit: ["EQUIDE Clear", "EQUIDE NEO Filter"], harga: 350000 },
  { kota: "Jakarta Barat", area: "Golf Lake", cluster: "Venetian Golf", favorit: ["EQUIDE Clear", "EQUIDE NEO Filter"], harga: 350000 },
  { kota: "Jakarta Barat", area: "Kalideres", cluster: "Permata Dalam", favorit: [], harga: 350000 },
  { kota: "Jakarta Barat", area: "Kalideres", cluster: "Taman Surya 1", favorit: [], harga: 300000 },
  { kota: "Jakarta Barat", area: "Kalideres", cluster: "Taman Surya 5", favorit: [], harga: 300000 },
  { kota: "Jakarta Barat", area: "Kamal", cluster: "Kamal", favorit: [], harga: 350000 },
  { kota: "Jakarta Barat", area: "Kebon Jeruk", cluster: "Business Park", favorit: [], harga: 450000 },
  { kota: "Jakarta Barat", area: "Kebon Jeruk", cluster: "Green Garden", favorit: [], harga: 450000 },
  { kota: "Jakarta Barat", area: "Kembangan", cluster: "Meruya", favorit: [], harga: 450000 },
  { kota: "Jakarta Barat", area: "Kembangan", cluster: "Permata Buana", favorit: [], harga: 400000 },
  { kota: "Jakarta Barat", area: "Kembangan", cluster: "Permata Puri Media", favorit: [], harga: 400000 },
  { kota: "Jakarta Barat", area: "Kembangan", cluster: "Puri Botanical Residence", favorit: [], harga: 400000 },
  { kota: "Jakarta Barat", area: "Kembangan", cluster: "Puri Kembang Harum", favorit: ["EQUIDE AquaCleanse"], harga: 400000 },
  { kota: "Jakarta Barat", area: "Tambora", cluster: "Jembatan Lima", favorit: [], harga: 500000 },
  { kota: "Jakarta Barat", area: "Tanjung Duren", cluster: "Tanjung Duren", favorit: [], harga: 500000 },

  { kota: "Jakarta Selatan", area: "Kebayoran Baru", cluster: "Gandaria Utara", favorit: [], harga: 550000 },
  { kota: "Jakarta Selatan", area: "Permata Hijau", cluster: "Permata Hijau", favorit: [], harga: 500000 },
  { kota: "Jakarta Selatan", area: "Tebet", cluster: "Tebet", favorit: [], harga: 550000 },

  { kota: "Jakarta Utara", area: "Ancol", cluster: "Metro Marina", favorit: [], harga: 600000 },
  { kota: "Jakarta Utara", area: "Kelapa Gading", cluster: "Villa Permata Gading", favorit: ["EQUIDE AquaCleanse"], harga: 600000 },
  { kota: "Jakarta Utara", area: "Penjaringan", cluster: "TPI", favorit: [], harga: 500000 },
  { kota: "Jakarta Utara", area: "PIK 1", cluster: "Florence", favorit: ["EQUIDE AquaCleanse"], harga: 500000 },
  { kota: "Jakarta Utara", area: "PIK 1", cluster: "Katamaran Indah", favorit: ["EQUIDE AquaCleanse"], harga: 500000 },
  { kota: "Jakarta Utara", area: "PIK 1", cluster: "Long Beach", favorit: ["EQUIDE AquaCleanse"], harga: 500000 },
  { kota: "Jakarta Utara", area: "PIK 1", cluster: "Pinisi Permai", favorit: ["EQUIDE AquaCleanse"], harga: 500000 },
  { kota: "Jakarta Utara", area: "PIK 1", cluster: "Taman Resort Mediterania", favorit: ["EQUIDE AquaCleanse"], harga: 500000 },
  { kota: "Jakarta Utara", area: "PIK 1", cluster: "Walet", favorit: ["EQUIDE AquaCleanse"], harga: 500000 },
  { kota: "Jakarta Utara", area: "Sunter", cluster: "Sunter", favorit: [], harga: 600000 },

  { kota: "Kabupaten Tangerang", area: "BSD", cluster: "Apt. Casa de Parco", favorit: ["EQUIDE Neo Filter"], harga: 500000 },
  { kota: "Kabupaten Tangerang", area: "BSD", cluster: "Bukit Golf", favorit: ["EQUIDE AquaCleanse"], harga: 500000 },
  { kota: "Kabupaten Tangerang", area: "BSD", cluster: "Foresta Albera", favorit: ["EQUIDE AquaCleanse"], harga: 500000 },
  { kota: "Kabupaten Tangerang", area: "BSD", cluster: "Foresta Fresco", favorit: ["EQUIDE AquaCleanse"], harga: 500000 },
  { kota: "Kabupaten Tangerang", area: "BSD", cluster: "Freja Chic", favorit: ["EQUIDE AquaCleanse"], harga: 500000 },
  { kota: "Kabupaten Tangerang", area: "BSD", cluster: "The ICON", favorit: ["EQUIDE AquaCleanse"], harga: 500000 },
  { kota: "Kabupaten Tangerang", area: "BSD", cluster: "The Zora", favorit: ["EQUIDE AquaCleanse"], harga: 500000 },
  { kota: "Kabupaten Tangerang", area: "Citra Raya", cluster: "Varenna", favorit: ["EQUIDE Clear", "EQUIDE NEO Filter", "holiv ClearWater", "holiv EasyClean"], harga: 600000 },
  { kota: "Kabupaten Tangerang", area: "Dadap", cluster: "Griya Dadap Estate", favorit: [], harga: 400000 },
  { kota: "Kabupaten Tangerang", area: "Dadap", cluster: "Pergudangan 99", favorit: [], harga: 400000 },
  { kota: "Kabupaten Tangerang", area: "Gading Serpong", cluster: "Amarillo Village", favorit: ["EQUIDE Clear", "EQUIDE AquaCleanse", "EQUIDE NEO Filter"], harga: 450000 },
  { kota: "Kabupaten Tangerang", area: "Gading Serpong", cluster: "Canary", favorit: ["EQUIDE Clear", "EQUIDE AquaCleanse", "EQUIDE NEO Filter"], harga: 450000 },
  { kota: "Kabupaten Tangerang", area: "Gading Serpong", cluster: "Carillo Residece", favorit: ["EQUIDE Clear", "EQUIDE AquaCleanse", "EQUIDE NEO Filter"], harga: 450000 },
  { kota: "Kabupaten Tangerang", area: "Gading Serpong", cluster: "Grisea", favorit: ["EQUIDE Clear", "EQUIDE AquaCleanse", "EQUIDE NEO Filter"], harga: 450000 },
  { kota: "Kabupaten Tangerang", area: "Gading Serpong", cluster: "Karelia Village", favorit: ["EQUIDE Clear", "EQUIDE AquaCleanse", "EQUIDE NEO Filter"], harga: 450000 },
  { kota: "Kabupaten Tangerang", area: "Gading Serpong", cluster: "Menaggio Village", favorit: ["EQUIDE Clear", "EQUIDE AquaCleanse", "EQUIDE NEO Filter"], harga: 450000 },
  { kota: "Kabupaten Tangerang", area: "Gading Serpong", cluster: "Michelia", favorit: ["EQUIDE Clear", "EQUIDE AquaCleanse", "EQUIDE NEO Filter"], harga: 450000 },
  { kota: "Kabupaten Tangerang", area: "Gading Serpong", cluster: "Milano Village", favorit: ["EQUIDE NEO Filter"], harga: 450000 },
  { kota: "Kabupaten Tangerang", area: "Gading Serpong", cluster: "PHG Jade", favorit: ["EQUIDE Clear", "EQUIDE AquaCleanse", "EQUIDE NEO Filter"], harga: 450000 },
  { kota: "Kabupaten Tangerang", area: "Gading Serpong", cluster: "Sektor 1E", favorit: ["EQUIDE Clear", "EQUIDE AquaCleanse", "EQUIDE NEO Filter"], harga: 450000 },
  { kota: "Kabupaten Tangerang", area: "Gading Serpong", cluster: "Thomson", favorit: ["EQUIDE Clear", "EQUIDE AquaCleanse", "EQUIDE NEO Filter"], harga: 450000 },
  { kota: "Kabupaten Tangerang", area: "Gading Serpong", cluster: "Turquoise", favorit: ["EQUIDE Clear", "EQUIDE AquaCleanse", "EQUIDE NEO Filter"], harga: 450000 },
  { kota: "Kabupaten Tangerang", area: "Karawaci", cluster: "Cendana Parc", favorit: ["EQUIDE Clear", "EQUIDE AquaCleanse", "EQUIDE NEO Filter"], harga: 450000 },
  { kota: "Kabupaten Tangerang", area: "PIK 2", cluster: "Pantai Bukit Villa", favorit: ["EQUIDE AquaCleanse", "EQUIDE NEO Filter", "EQUIDE Clear"], harga: 500000 },
  { kota: "Kabupaten Tangerang", area: "PIK 2", cluster: "Villa Pasir Putih", favorit: ["EQUIDE AquaCleanse", "EQUIDE NEO Filter", "EQUIDE Clear"], harga: 500000 },

  { kota: "Kota Tangerang", area: "Ciledug", cluster: "Fortune Breeze", favorit: ["EQUIDE AquaCleanse"], harga: 450000 },
  { kota: "Kota Tangerang", area: "Cipondoh", cluster: "Metland Puri", favorit: ["EQUIDE AquaCleanse"], harga: 400000 },
  { kota: "Kota Tangerang", area: "Cipondoh", cluster: "Poris Garden", favorit: [], harga: 400000 },
  { kota: "Kota Tangerang", area: "Greenlake City", cluster: "Cluster Asia", favorit: [], harga: 400000 },
  { kota: "Kota Tangerang", area: "Karang Tengah", cluster: "Puri 11", favorit: ["EQUIDE AquaCleanse", "EQUIDE NEO Filter"], harga: 400000 },
  { kota: "Kota Tangerang", area: "Karawaci", cluster: "Karawaci", favorit: [], harga: 450000 },
  { kota: "Kota Tangerang", area: "Sepatan", cluster: "Emerald Residence", favorit: ["EQUIDE Clear", "EQUIDE NEO Filter"], harga: 500000 },
  { kota: "Kota Tangerang", area: "Taman Royal", cluster: "Pinus Ext", favorit: [], harga: 400000 },

  { kota: "Tangerang Selatan", area: "Bintaro", cluster: "Citra Garden Calamus", favorit: [], harga: 500000 },
  { kota: "Tangerang Selatan", area: "Bintaro", cluster: "Sektor 3A", favorit: [], harga: 500000 },
  { kota: "Tangerang Selatan", area: "Ciputat", cluster: "Umar Residence II", favorit: [], harga: 550000 },
  { kota: "Tangerang Selatan", area: "Ciputat", cluster: "Ciputat", favorit: [], harga: 550000 },
  { kota: "Tangerang Selatan", area: "Ciputat", cluster: "Ciputat", favorit: [], harga: 550000 },
  { kota: "Tangerang Selatan", area: "Pondok Aren", cluster: "Pondok Maharta", favorit: [], harga: 500000 },
  { kota: "Tangerang Selatan", area: "Serpong", cluster: "Dammara Graha Raya", favorit: ["EQUIDE Clear", "EQUIDE AquaCleanse", "EQUIDE NEO Filter"], harga: 450000 }
];